stages:
  - build
  - test

cache:
  paths:
    - Pods

before_script:
  - bundle install

build_project:
  stage: build
  script:
    - bundle exec fastlane install_depencies
  tags: 
    - ios

test_project:
  stage: test
  script:
    - bundle exec fastlane tests
  tags: 
    - ios